// <auto-generated />
namespace WebMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20171027_sdp03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20171027_sdp03));
        
        string IMigrationMetadata.Id
        {
            get { return "201710270845304_20171027_sdp03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
