// <auto-generated />
namespace WebMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20171124_sdp01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20171124_sdp01));
        
        string IMigrationMetadata.Id
        {
            get { return "201711240855538_20171124_sdp01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
