// <auto-generated />
namespace WebMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20180206_sdp06 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180206_sdp06));
        
        string IMigrationMetadata.Id
        {
            get { return "201802060541358_20180206_sdp06"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
