// <auto-generated />
namespace WebMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20180315_sdp04 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20180315_sdp04));
        
        string IMigrationMetadata.Id
        {
            get { return "201803150613481_20180315_sdp04"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
